<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Infrastructure\Persistence\Models\CountryModel;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['id' => 'AF', 'name' => 'Afganistán'],
            ['id' => 'AL', 'name' => 'Albania'],
            ['id' => 'DE', 'name' => 'Alemania'],
            ['id' => 'AD', 'name' => 'Andorra'],
            ['id' => 'AO', 'name' => 'Angola'],
            ['id' => 'AG', 'name' => 'Antigua y Barbuda'],
            ['id' => 'SA', 'name' => 'Arabia Saudí'],
            ['id' => 'DZ', 'name' => 'Argelia'],
            ['id' => 'AR', 'name' => 'Argentina'],
            ['id' => 'AM', 'name' => 'Armenia'],
            ['id' => 'AU', 'name' => 'Australia'],
            ['id' => 'AT', 'name' => 'Austria'],
            ['id' => 'AZ', 'name' => 'Azerbaiyán'],
            ['id' => 'BS', 'name' => 'Bahamas'],
            ['id' => 'BH', 'name' => 'Baréin'],
            ['id' => 'BD', 'name' => 'Bangladés'],
            ['id' => 'BB', 'name' => 'Barbados'],
            ['id' => 'BE', 'name' => 'Bélgica'],
            ['id' => 'BZ', 'name' => 'Belice'],
            ['id' => 'BJ', 'name' => 'Benín'],
            ['id' => 'BY', 'name' => 'Bielorrusia'],
            ['id' => 'MM', 'name' => 'Birmania'],
            ['id' => 'BO', 'name' => 'Bolivia'],
            ['id' => 'BA', 'name' => 'Bosnia y Herzegovina'],
            ['id' => 'BW', 'name' => 'Botsuana'],
            ['id' => 'BR', 'name' => 'Brasil'],
            ['id' => 'BN', 'name' => 'Brunéi'],
            ['id' => 'BG', 'name' => 'Bulgaria'],
            ['id' => 'BF', 'name' => 'Burkina Faso'],
            ['id' => 'BI', 'name' => 'Burundi'],
            ['id' => 'BT', 'name' => 'Bután'],
            ['id' => 'CV', 'name' => 'Cabo Verde'],
            ['id' => 'KH', 'name' => 'Camboya'],
            ['id' => 'CM', 'name' => 'Camerún'],
            ['id' => 'CA', 'name' => 'Canadá'],
            ['id' => 'QA', 'name' => 'Catar'],
            ['id' => 'TD', 'name' => 'Chad'],
            ['id' => 'CL', 'name' => 'Chile'],
            ['id' => 'CN', 'name' => 'China'],
            ['id' => 'CY', 'name' => 'Chipre'],
            ['id' => 'CO', 'name' => 'Colombia'],
            ['id' => 'KM', 'name' => 'Comoras'],
            ['id' => 'CG', 'name' => 'Congo'],
            ['id' => 'CD', 'name' => 'Congo (RDC)'],
            ['id' => 'KR', 'name' => 'Corea del Sur'],
            ['id' => 'KP', 'name' => 'Corea del Norte'],
            ['id' => 'CI', 'name' => 'Costa de Marfil'],
            ['id' => 'CR', 'name' => 'Costa Rica'],
            ['id' => 'HR', 'name' => 'Croacia'],
            ['id' => 'CU', 'name' => 'Cuba'],
            ['id' => 'DK', 'name' => 'Dinamarca'],
            ['id' => 'DJ', 'name' => 'Yibuti'],
            ['id' => 'DM', 'name' => 'Dominica'],
            ['id' => 'EC', 'name' => 'Ecuador'],
            ['id' => 'EG', 'name' => 'Egipto'],
            ['id' => 'SV', 'name' => 'El Salvador'],
            ['id' => 'AE', 'name' => 'Emiratos Árabes Unidos'],
            ['id' => 'ER', 'name' => 'Eritrea'],
            ['id' => 'SK', 'name' => 'Eslovaquia'],
            ['id' => 'SI', 'name' => 'Eslovenia'],
            ['id' => 'ES', 'name' => 'España'],
            ['id' => 'US', 'name' => 'Estados Unidos'],
            ['id' => 'EE', 'name' => 'Estonia'],
            ['id' => 'ET', 'name' => 'Etiopía'],
            ['id' => 'PH', 'name' => 'Filipinas'],
            ['id' => 'FI', 'name' => 'Finlandia'],
            ['id' => 'FJ', 'name' => 'Fiyi'],
            ['id' => 'FR', 'name' => 'Francia'],
            ['id' => 'GA', 'name' => 'Gabón'],
            ['id' => 'GM', 'name' => 'Gambia'],
            ['id' => 'GE', 'name' => 'Georgia'],
            ['id' => 'GH', 'name' => 'Ghana'],
            ['id' => 'GD', 'name' => 'Granada'],
            ['id' => 'GR', 'name' => 'Grecia'],
            ['id' => 'GT', 'name' => 'Guatemala'],
            ['id' => 'GN', 'name' => 'Guinea'],
            ['id' => 'GQ', 'name' => 'Guinea Ecuatorial'],
            ['id' => 'GW', 'name' => 'Guinea-Bisáu'],
            ['id' => 'GY', 'name' => 'Guyana'],
            ['id' => 'HT', 'name' => 'Haití'],
            ['id' => 'HN', 'name' => 'Honduras'],
            ['id' => 'HU', 'name' => 'Hungría'],
            ['id' => 'IN', 'name' => 'India'],
            ['id' => 'ID', 'name' => 'Indonesia'],
            ['id' => 'IQ', 'name' => 'Irak'],
            ['id' => 'IR', 'name' => 'Irán'],
            ['id' => 'IE', 'name' => 'Irlanda'],
            ['id' => 'IS', 'name' => 'Islandia'],
            ['id' => 'IL', 'name' => 'Israel'],
            ['id' => 'IT', 'name' => 'Italia'],
            ['id' => 'JM', 'name' => 'Jamaica'],
            ['id' => 'JP', 'name' => 'Japón'],
            ['id' => 'JO', 'name' => 'Jordania'],
            ['id' => 'KZ', 'name' => 'Kazajistán'],
            ['id' => 'KE', 'name' => 'Kenia'],
            ['id' => 'KG', 'name' => 'Kirguistán'],
            ['id' => 'KI', 'name' => 'Kiribati'],
            ['id' => 'KW', 'name' => 'Kuwait'],
            ['id' => 'LA', 'name' => 'Laos'],
            ['id' => 'LS', 'name' => 'Lesoto'],
            ['id' => 'LV', 'name' => 'Letonia'],
            ['id' => 'LB', 'name' => 'Líbano'],
            ['id' => 'LR', 'name' => 'Liberia'],
            ['id' => 'LY', 'name' => 'Libia'],
            ['id' => 'LI', 'name' => 'Liechtenstein'],
            ['id' => 'LT', 'name' => 'Lituania'],
            ['id' => 'LU', 'name' => 'Luxemburgo'],
            ['id' => 'MK', 'name' => 'Macedonia del Norte'],
            ['id' => 'MG', 'name' => 'Madagascar'],
            ['id' => 'MY', 'name' => 'Malasia'],
            ['id' => 'MW', 'name' => 'Malaui'],
            ['id' => 'MV', 'name' => 'Maldivas'],
            ['id' => 'ML', 'name' => 'Mali'],
            ['id' => 'MT', 'name' => 'Malta'],
            ['id' => 'MA', 'name' => 'Marruecos'],
            ['id' => 'MU', 'name' => 'Mauricio'],
            ['id' => 'MR', 'name' => 'Mauritania'],
            ['id' => 'MX', 'name' => 'México'],
            ['id' => 'FM', 'name' => 'Micronesia'],
            ['id' => 'MD', 'name' => 'Moldavia'],
            ['id' => 'MC', 'name' => 'Mónaco'],
            ['id' => 'MN', 'name' => 'Mongolia'],
            ['id' => 'ME', 'name' => 'Montenegro'],
            ['id' => 'MZ', 'name' => 'Mozambique'],
            ['id' => 'NA', 'name' => 'Namibia'],
            ['id' => 'NR', 'name' => 'Nauru'],
            ['id' => 'NP', 'name' => 'Nepal'],
            ['id' => 'NI', 'name' => 'Nicaragua'],
            ['id' => 'NE', 'name' => 'Níger'],
            ['id' => 'NG', 'name' => 'Nigeria'],
            ['id' => 'NO', 'name' => 'Noruega'],
            ['id' => 'NZ', 'name' => 'Nueva Zelanda'],
            ['id' => 'OM', 'name' => 'Omán'],
            ['id' => 'NL', 'name' => 'Países Bajos'],
            ['id' => 'PK', 'name' => 'Pakistán'],
            ['id' => 'PW', 'name' => 'Palaos'],
            ['id' => 'PA', 'name' => 'Panamá'],
            ['id' => 'PG', 'name' => 'Papúa Nueva Guinea'],
            ['id' => 'PY', 'name' => 'Paraguay'],
            ['id' => 'PE', 'name' => 'Perú'],
            ['id' => 'PL', 'name' => 'Polonia'],
            ['id' => 'PT', 'name' => 'Portugal'],
            ['id' => 'PR', 'name' => 'Puerto Rico'],
            ['id' => 'GB', 'name' => 'Reino Unido'],
            ['id' => 'CF', 'name' => 'República Centroafricana'],
            ['id' => 'CZ', 'name' => 'República Checa'],
            ['id' => 'DO', 'name' => 'República Dominicana'],
            ['id' => 'RW', 'name' => 'Ruanda'],
            ['id' => 'RO', 'name' => 'Rumanía'],
            ['id' => 'RU', 'name' => 'Rusia'],
            ['id' => 'WS', 'name' => 'Samoa'],
            ['id' => 'SM', 'name' => 'San Marino'],
            ['id' => 'ST', 'name' => 'Santo Tomé y Príncipe'],
            ['id' => 'SN', 'name' => 'Senegal'],
            ['id' => 'RS', 'name' => 'Serbia'],
            ['id' => 'SC', 'name' => 'Seychelles'],
            ['id' => 'SL', 'name' => 'Sierra Leona'],
            ['id' => 'SG', 'name' => 'Singapur'],
            ['id' => 'SY', 'name' => 'Siria'],
            ['id' => 'SO', 'name' => 'Somalia'],
            ['id' => 'LK', 'name' => 'Sri Lanka'],
            ['id' => 'SZ', 'name' => 'Suazilandia'],
            ['id' => 'ZA', 'name' => 'Sudáfrica'],
            ['id' => 'SD', 'name' => 'Sudán'],
            ['id' => 'SS', 'name' => 'Sudán del Sur'],
            ['id' => 'SE', 'name' => 'Suecia'],
            ['id' => 'CH', 'name' => 'Suiza'],
            ['id' => 'SR', 'name' => 'Surinam'],
            ['id' => 'TH', 'name' => 'Tailandia'],
            ['id' => 'TW', 'name' => 'Taiwán'],
            ['id' => 'TZ', 'name' => 'Tanzania'],
            ['id' => 'TJ', 'name' => 'Tayikistán'],
            ['id' => 'TL', 'name' => 'Timor Oriental'],
            ['id' => 'TG', 'name' => 'Togo'],
            ['id' => 'TO', 'name' => 'Tonga'],
            ['id' => 'TT', 'name' => 'Trinidad y Tobago'],
            ['id' => 'TN', 'name' => 'Túnez'],
            ['id' => 'TM', 'name' => 'Turkmenistán'],
            ['id' => 'TR', 'name' => 'Turquía'],
            ['id' => 'TV', 'name' => 'Tuvalu'],
            ['id' => 'UA', 'name' => 'Ucrania'],
            ['id' => 'UG', 'name' => 'Uganda'],
            ['id' => 'UY', 'name' => 'Uruguay'],
            ['id' => 'UZ', 'name' => 'Uzbekistán'],
            ['id' => 'VU', 'name' => 'Vanuatu'],
            ['id' => 'VA', 'name' => 'Vaticano'],
            ['id' => 'VE', 'name' => 'Venezuela'],
            ['id' => 'VN', 'name' => 'Vietnam'],
            ['id' => 'YE', 'name' => 'Yemen'],
            ['id' => 'ZM', 'name' => 'Zambia'],
            ['id' => 'ZW', 'name' => 'Zimbabue'],
        ];

        foreach ($countries as $country) {
            CountryModel::updateOrCreate(
                ['id' => $country['id']],
                ['name' => $country['name']]
            );
        }
    }
}
